# Creación del token a usar por el service account para ejecutar los workflows
# Más información: https://argo-workflows.readthedocs.io/en/latest/access-token/
apiVersion: v1
kind: Secret
metadata:
  name: argo-user.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-user
type: kubernetes.io/service-account-token